pipeline {
  agent {
    node{
      label 'slave'
    }
  }
  stages {
    stage('Hello') {
      steps {
        sh 'java -version'
        echo "Get Working Directory"
        sh 'pwd'
      }
    }
  }
}
