pipeline {
  agent {
    docker {image 'jenkins/slave:latest'}
  }
  stages {
    stage('Hello') {
      steps {
        sh 'java -version'
        echo "Get Working Directory"
        sh 'pwd'
      }
    }
  }
}
